<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.jenkins-ci.plugins</groupId>
		<artifactId>plugin</artifactId>
		<version>6.2221.va_045130417c9</version>
		<relativePath />
	</parent>

	<groupId>org.jenkins-ci.plugins</groupId>
	<artifactId>bitbucket-oauth</artifactId>
	<version>0.19-SNAPSHOT</version>
	<name>Bitbucket OAuth Plugin</name>
	<description>A Jenkins authentication plugin that delegates to Bitbucket OAuth</description>
	<packaging>hpi</packaging>

	<url>https://github.com/jenkinsci/bitbucket-oauth-plugin</url>

	<scm>
		<connection>scm:git:git@github.com:jenkinsci/bitbucket-oauth-plugin.git</connection>
		<developerConnection>scm:git:git@github.com:jenkinsci/bitbucket-oauth-plugin.git</developerConnection>
		<url>https://github.com/jenkinsci/bitbucket-oauth-plugin</url>
		<tag>HEAD</tag>
	</scm>

	<licenses>
		<license>
			<name>MIT license</name>
			<comments>All source code is under the MIT license.</comments>
		</license>
	</licenses>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.jenkins.tools.bom</groupId>
				<artifactId>bom-${jenkins.baseline}.x</artifactId>
				<version>6815.v1fb_2a_fee3765</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<repositories>
		<repository>
			<id>repo.jenkins-ci.org</id>
			<url>https://repo.jenkins-ci.org/public/</url>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>repo.jenkins-ci.org</id>
			<url>https://repo.jenkins-ci.org/public/</url>
		</pluginRepository>
	</pluginRepositories>

	<dependencies>
		<dependency>
			<groupId>io.jenkins.plugins</groupId>
			<artifactId>gson-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.scribe</groupId>
			<artifactId>scribe</artifactId>
			<version>1.3.7</version>
		</dependency>
		<dependency>
			<groupId>org.wiremock</groupId>
			<artifactId>wiremock-standalone</artifactId>
			<version>3.13.2</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.jenkins-ci.tools</groupId>
				<artifactId>maven-hpi-plugin</artifactId>
				<extensions>true</extensions>
				<configuration>
					<compatibleSinceVersion>0.8</compatibleSinceVersion>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<!-- https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/ -->
		<jenkins.baseline>2.541</jenkins.baseline>
		<jenkins.version>${jenkins.baseline}.3</jenkins.version>
		<ban-commons-lang-2.skip>false</ban-commons-lang-2.skip>
		<ban-junit4-imports.skip>false</ban-junit4-imports.skip>
	</properties>
</project>
